version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME:-./localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"